"""Test for dpres_scraper.scrapers/__init__.py. The purpose of this test is to make sure
that all scrapers are able to be found."""

from dpres_scraper.iterator import iter_scrapers
import pytest


@pytest.mark.parametrize(
    ["mimetype", "version", "charset", "scraper_classes"],
    [
        ("application/x-spss-por", "", "", ["Pspp"]),
        ("application/warc", "1.0", "", ["WarcWarctools"]),
        ("text/csv", "", "UTF-8", ["Csv", "TextFileMagic"]),
        ("text/csv", "", "UTF-16", ["Csv", "TextFileMagic"]),
        ("text/plain", "", "ISO-8859-15", ["TextFileMagic"]),
        ("text/plain", "", "UTF-16", ["TextFileMagic"]),
        ("text/plain", "", "UTF-8", ["TextFileMagic", "TextFileMagic"]),
        ("video/mpeg", "1", "", ["MpegMediainfo"]),
        ("video/mpeg", "2", "", ["MpegMediainfo"]),
        ("video/mp4", "", "", ["MpegMediainfo"]),
        ("application/pdf", "1.2", "", ["PdfJHove"]),
        ("application/pdf", "1.3", "", ["PdfJHove"]),
        ("application/pdf", "1.4", "", ["PdfJHove"]),
        ("application/pdf", "1.5", "", ["PdfJHove"]),
        ("application/pdf", "1.6", "", ["PdfJHove"]),
        ("application/pdf", "A-1a", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "A-1b", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "A-2a", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "A-2b", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "A-2u", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "A-3a", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "A-3b", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "A-3u", "", ["GhostScript", "VeraPdf"]),
        ("application/pdf", "1.7", "", ["GhostScript"]),
        ("image/tiff", "6.0", "", ["TiffJHove", "ImageFileMagic", "TiffPil", "TiffWand"]),
        ("image/jpeg", "1.00", "", ["JpegJHove", "ImageFileMagic", "JpegPil", "ImageWand"]),
        ("image/jpeg", "1.01", "", ["JpegJHove", "ImageFileMagic", "JpegPil", "ImageWand"]),
        ("image/jpeg", "1.02", "", ["JpegJHove", "ImageFileMagic", "JpegPil", "ImageWand"]),
        ("image/gif", "1987a", "", ["GifJHove", "ImagePil", "ImageWand"]),
        ("image/gif", "1989a", "", ["GifJHove", "ImagePil", "ImageWand"]),
        ("text/html", "4.01", "UTF-8", ["HtmlJHove", "HtmlFileMagic"]),
        ("text/html", "4.01", "UTF-16", ["HtmlJHove", "HtmlFileMagic"]),
        ("text/html", "5.0", "UTF-8", ["Vnu", "XmlEncoding", "HtmlFileMagic"]),
        ("text/html", "5.0", "UTF-16", ["Vnu", "XmlEncoding", "HtmlFileMagic"]),
        ("image/png", "1.2", "", ["Pngcheck", "ImageFileMagic", "ImagePil", "ImageWand"]),
        ("application/warc", "0.17", "", ["WarcWarctools"]),
        ("application/warc", "0.18", "", ["WarcWarctools"]),
        ("application/warc", "1.0", "", ["WarcWarctools"]),
        ("application/x-internet-archive", "1.0", "", ["ArcWarctools"]),
        ("application/x-internet-archive", "1.1", "", ["ArcWarctools"]),
        ("text/xml", "1.0", "UTF-8",
         ["Xmllint", "XmlEncoding", "XmlFileMagic"]),
        ("text/xml", "1.0", "UTF-16",
         ["Xmllint", "XmlEncoding", "XmlFileMagic"]),
        ("application/xhtml+xml", "1.0", "UTF-8",
         ["HtmlJHove", "HtmlFileMagic"]),
        ("application/xhtml+xml", "1.0", "UTF-16",
         ["HtmlJHove", "HtmlFileMagic"]),
        ("application/xhtml+xml", "1.1", "UTF-8",
         ["HtmlJHove", "HtmlFileMagic"]),
        ("application/xhtml+xml", "1.1", "UTF-16",
         ["HtmlJHove", "HtmlFileMagic"]),
        ("audio/x-wav", "", "", ["WavJHove"]),
        ("audio/x-wav", "2", "", ["WavJHove"]),
        ("application/vnd.oasis.opendocument.text",
         "1.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.text", "1.1", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.text", "1.2", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.spreadsheet", "1.0", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.spreadsheet", "1.1", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.spreadsheet", "1.2", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.presentation", "1.0", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.presentation", "1.1", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.presentation", "1.2", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.graphics", "1.0", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.graphics", "1.1", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.graphics", "1.2", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.formula", "1.0", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.formula", "1.1", "",
         ["Office", "BinaryFileMagic"]),
        ("application/vnd.oasis.opendocument.formula", "1.2", "",
         ["Office", "BinaryFileMagic"]),
        ("application/msword", "8.0", "", ["Office", "BinaryFileMagic"]),
        ("application/msword", "8.5", "", ["Office", "BinaryFileMagic"]),
        ("application/msword", "9.0", "", ["Office", "BinaryFileMagic"]),
        ("application/msword", "10.0", "", ["Office", "BinaryFileMagic"]),
        ("application/msword", "11.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-excel", "8.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-excel", "9.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-excel", "10.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-excel", "11.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-powerpoint", "8.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-powerpoint", "9.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-powerpoint", "10.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.ms-powerpoint", "11.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.wordprocessingml."
         "document", "12.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.wordprocessingml."
         "document", "14.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.wordprocessingml."
         "document", "15.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
         "12.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
         "14.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
         "15.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.presentationml."
         "presentation", "12.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.presentationml."
         "presentation", "14.0", "", ["Office", "BinaryFileMagic"]),
        ("application/vnd.openxmlformats-officedocument.presentationml."
         "presentation", "15.0", "", ["Office", "BinaryFileMagic"]),
    ])
def tests_iter_scrapers(mimetype, version, charset, scraper_classes):
    """
    Test for scraper discovery.
    """
    scrapers = iter_scrapers("/dev/null", mimetype, version)
    assert set(
        [x.__class__.__name__ for x in scrapers]) == set(scraper_classes)
