"""Common dictionaries
"""

PRONOM_DICT = {
    'x-fmt/18': ('text/csv', ''),
    'fmt/483': ('application/epub+zip', None),  # does not result version
    'fmt/102': ('application/xhtml+xml', '1.0'),
    'fmt/103': ('application/xhtml+xml', '1.1'),
    'fmt/101': ('text/xml', '1.0'),
    'fmt/100': ('text/html', '4.01'),
    'fmt/471': ('text/html', '5.0'),
    'fmt/136': ('application/vnd.oasis.opendocument.text', '1.0'),
    'fmt/290': ('application/vnd.oasis.opendocument.text', '1.1'),
    'fmt/291': ('application/vnd.oasis.opendocument.text', '1.2'),
    'fmt/137': ('application/vnd.oasis.opendocument.spreadsheet', '1.0'),
    'fmt/294': ('application/vnd.oasis.opendocument.spreadsheet', '1.1'),
    'fmt/295': ('application/vnd.oasis.opendocument.spreadsheet', '1.2'),
    'fmt/138': ('application/vnd.oasis.opendocument.presentation', '1.0'),
    'fmt/292': ('application/vnd.oasis.opendocument.presentation', '1.1'),
    'fmt/293': ('application/vnd.oasis.opendocument.presentation', '1.2'),
    'fmt/139': ('application/vnd.oasis.opendocument.graphics', '1.0'),
    'fmt/296': ('application/vnd.oasis.opendocument.graphics', '1.1'),
    'fmt/297': ('application/vnd.oasis.opendocument.graphics', '1.2'),
    'fmt/95': ('application/pdf', 'A-1a'),
    'fmt/354': ('application/pdf', 'A-1b'),
    'fmt/476': ('application/pdf', 'A-2a'),
    'fmt/477': ('application/pdf', 'A-2b'),
    'fmt/478': ('application/pdf', 'A-2u'),
    'fmt/479': ('application/pdf', 'A-3a'),
    'fmt/480': ('application/pdf', 'A-3b'),
    'fmt/481': ('application/pdf', 'A-3u'),
    'x-fmt/111': ('text/plain', ''),
    'x-fmt/135': ('audio/x-aiff', '1.3'),
    'fmt/527': ('audio/x-wav', '2'),
    'fmt/279': ('audio/flac', '1.2.1'),
    'fmt/199': (None, ''),  # video/mp4 or audio/mp4
    'fmt/141': ('audio/x-wav', ''),
    'fmt/541': ('image/x-dpx', '2.0'),
    'x-fmt/392': (None, ''),  # video/jpeg2000 or image/jp2
    'fmt/438': ('image/tiff', '1.3'),
    'fmt/730': ('image/tiff', '1.4'),
    'fmt/42': ('image/jpeg', '1.00'),
    'fmt/43': ('image/jpeg', '1.01'),
    'fmt/44': ('image/jpeg', '1.02'),
    'x-fmt/398': ('image/jpeg', '2.0'),
    'x-fmt/390': ('image/jpeg', '2.1'),
    'x-fmt/391': ('image/jpeg', '2.2'),
    'fmt/645': ('image/jpeg', '2.2.1'),
    'fmt/353': ('image/tiff', '6.0'),
    'fmt/13': ('image/png', '1.2'),
    'x-fmt/219': ('application/x-internet-archive', '1.0'),
    'fmt/410': ('application/x-internet-archive', '1.1'),
    'fmt/289': ('application/warc', None),  # does not result version
    'fmt/155': ('image/tiff', '1.0'),
    'x-fmt/227': ('application/gml+xml', '3.2.1'),
    'fmt/244': ('application/vnd.google-earth.kml+xml', '2.3'),
    'fmt/997': ('application/x-spss-por', ''),
    'fmt/40': ('application/msword', '11.0'),
    'fmt/412': ('application/vnd.openxmlformats-officedocument.'
                'wordprocessingml.document', '15.0'),
    'fmt/61': ('application/vnd.ms-excel', '8.0'),
    'fmt/62': ('application/vnd.ms-excel', '11.0'),
    'fmt/214': ('application/vnd.openxmlformats-officedocument.'
                'spreadsheetml.sheet', '15.0'),
    'fmt/126': ('application/vnd.ms-powerpoint', '11.0'),
    'fmt/215': ('application/vnd.openxmlformats-officedocument.'
                'presentationml.presentation', '15.0'),
    'fmt/16': ('application/pdf', '1.2'),
    'fmt/17': ('application/pdf', '1.3'),
    'fmt/18': ('application/pdf', '1.4'),
    'fmt/19': ('application/pdf', '1.5'),
    'fmt/20': ('application/pdf', '1.6'),
    'fmt/276': ('application/pdf', '1.7'),
    'x-fmt/136': ('audio/x-aiff', ''),
    'fmt/134': ('audio/mpeg', None),  # does not result version
    'fmt/132': ('audio/x-ms-wma', '9'),
    'x-fmt/152': ('video/dv', ''),
    'fmt/649': ('video/mpeg', '1'),
    'fmt/640': ('video/mpeg', '2'),
    'fmt/133': ('video/x-ms-wmv', '9'),
    'fmt/124': ('application/postscript', '3.0'),
    'fmt/3': ('image/gif', '1987a'),
    'fmt/4': ('image/gif', '1989a'),
    'fmt/131': ('video/x-ms-asf', ''),
    'fmt/5': ('video/avi', ''),
    'x-fmt/385': ('video/MP1S', ''),
    'x-fmt/386': ('video/MP2P', ''),
    'fmt/585': ('video/MP2T', ''),
    'fmt/200': ('application/mxf', ''),
    'fmt/337': ('video/mj2', ''),
    'x-fmt/384': ('video/quicktime', '')
}
